---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# posologyr

<!-- badges: start -->
<!-- badges: end -->

## Overview

`posologyr` is an R package for drug treatment individualisation, taking advantage of population pharmacokinetics (popPK), patient characteristics, and the results of therapeutic drug monitoring.

`posologyr` provides functions for estimating the pharmacokinetic (PK) parameters:

+ `poso_simu_pop()` for estimating the a priori distributions of popPK parameters by Monte-Carlo simulations
+ `poso_estim_map()` for computing the Maximum A Posteriori (MAP), aka Empirical Bayes Estimates (EBE), of individual PK parameters from the results of therapeutic drug monitoring
+ `poso_estim_mcmc()` for estimating the posterior distributions of individual PK parameters by Markov Chain Monte Carlo (MCMC)

Functions for dosage optimisation are included in `posologyr`:

+ `poso_time_cmin()` computes the time needed to reach a target trough concentration (Cmin)
+ `poso_dose_auc()` estimates the optimal dose to reach a target AUC
+ `poso_dose_ctime()` estimates the optimal dose to reach a target concentration at any given time

Posologyr requires a popPK model written in the `RxODE` mini-language.

## Installation

You can install the development version of `posologyr` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("levenc/posologyr")
```

## Example

An example of a dosage adjustment with posologyr is available in the following vignette: `vignette("case_study_amikacin")` 

## Acknowledgments
`posologyr` takes advantage of the simulation framework provided by the  [RxODE](https://github.com/nlmixrdevelopment/RxODE) package.

`posologyr`'s estimation functions were based on [Marc Lavielle's shiny app]( http://shiny.webpopix.org/mcmc/bayes1/)
